#!/usr/bin/env python3
"""Generate docs/tools.md from the live MCP tool catalog.

Parameters are read from the servers' actual `tools/list` input schemas — the
same JSON an MCP client sees — so the document cannot drift from the tools,
including their argument names, types, and requiredness. CI-checkable:
`--stdout` must match the committed file byte-for-byte.
"""

from __future__ import annotations

import argparse
import asyncio
import html
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPO))

import mcp  # noqa: E402

from ads_mcp.config import Config  # noqa: E402
from ads_mcp.server import create_server  # noqa: E402
from ads_mcp.tools.registry import all_tool_specs  # noqa: E402

KIND_TITLES = {
    "read": "Read tools (registered in every mode)",
    "mutation": "Mutation tools (write mode only — every call returns a plan)",
    "apply": "Apply (the single execution path)",
}


def _config(read_only: bool) -> Config:
    """A configuration object built directly, so doc generation needs no
    credentials, no environment, and no network."""
    return Config(
        developer_token="doc-generation",
        customer_id="0000000000",
        login_customer_id=None,
        credentials_path="",
        token_path="",
        read_only=read_only,
        require_dry_run=True,
        max_daily_budget=None,
        max_bid_increase_pct=None,
        max_first_bid=None,
        audit_log=None,
        retry_base_seconds=1.0,
        plan_ttl_seconds=900.0,
        row_limit=1000,
    )


async def _list_tools(read_only: bool) -> dict:
    server = create_server(_config(read_only), client=object(), clock=lambda: 0.0)
    async with mcp.Client(server) as client:
        listed = await client.list_tools()
        return {t.name: t for t in listed.tools}


def _schemas() -> dict:
    tools = asyncio.run(_list_tools(read_only=True))
    tools.update(asyncio.run(_list_tools(read_only=False)))
    return tools


def _type_name(schema: dict) -> str:
    if "anyOf" in schema:
        parts = [_type_name(s) for s in schema["anyOf"] if s.get("type") != "null"]
        return " | ".join(dict.fromkeys(parts)) or "any"
    kind = schema.get("type", "any")
    if kind == "array":
        return f"array<{_type_name(schema.get('items', {}))}>"
    return kind


def render() -> str:
    specs = all_tool_specs()
    tools = _schemas()
    lines = [
        "# ads-mcp tool catalog",
        "",
        "Generated by `scripts/gen_tools_md.py` from the live MCP tool "
        "catalog — do not edit by hand. Regenerate with "
        "`python scripts/gen_tools_md.py`.",
        "",
        "Mutation tools never execute: each returns a **plan** that "
        "`confirm_and_apply` alone can carry out, after a dry-run preview.",
        "",
    ]
    for kind in ("read", "mutation", "apply"):
        lines += [f"## {KIND_TITLES[kind]}", ""]
        for spec in sorted((s for s in specs if s.kind == kind), key=lambda s: s.name):
            lines += [f"### `{spec.name}`", "", spec.description, ""]
            tool = tools.get(spec.name)
            schema = getattr(tool, "input_schema", None) or {}
            props = schema.get("properties") or {}
            if not props:
                lines += ["*No parameters.*", ""]
                continue
            required = set(schema.get("required") or ())
            lines += ["| Parameter | Type | Required | Default |", "|---|---|---|---|"]
            for name, prop in props.items():
                default = prop.get("default", None)
                shown = "—" if default is None else f"`{default}`"
                type_cell = html.escape(_type_name(prop)).replace("|", r"\|")
                lines.append(
                    f"| `{name}` | {type_cell} | "
                    f"{'yes' if name in required else 'no'} | {shown} |"
                )
            lines.append("")
    return "\n".join(lines).rstrip() + "\n"


def main(argv=None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--stdout", action="store_true", help="print instead of writing")
    args = parser.parse_args(argv)
    content = render()
    if args.stdout:
        sys.stdout.write(content)
    else:
        (REPO / "docs").mkdir(exist_ok=True)
        (REPO / "docs" / "tools.md").write_text(content)
        print(f"wrote docs/tools.md ({len(content)} bytes)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
